// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBo2srGcj6qbXoje5JRY_yvIzGn6PbJcF0',
    appId: '1:440253389107:web:47fc3452cd3444c0dec646',
    messagingSenderId: '440253389107',
    projectId: 'plmobile',
    authDomain: 'plmobile.firebaseapp.com',
    storageBucket: 'plmobile.appspot.com',
    measurementId: 'G-H35S9EESVD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtAl5VluU4efcdIZag549p0-yOaTfni2I',
    appId: '1:440253389107:android:a25ec4e2b868de1fdec646',
    messagingSenderId: '440253389107',
    projectId: 'plmobile',
    storageBucket: 'plmobile.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUpe_MQp8-Rjof2loDW-ODqd8NscHJ0pk',
    appId: '1:440253389107:ios:44f8d194211d3061dec646',
    messagingSenderId: '440253389107',
    projectId: 'plmobile',
    storageBucket: 'plmobile.appspot.com',
    iosBundleId: 'plmobile.plmobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBUpe_MQp8-Rjof2loDW-ODqd8NscHJ0pk',
    appId: '1:440253389107:ios:681a28d7c5863f22dec646',
    messagingSenderId: '440253389107',
    projectId: 'plmobile',
    storageBucket: 'plmobile.appspot.com',
    iosBundleId: 'plmobile.plmobile.RunnerTests',
  );
}
